/* eslint-disable eslint-comments/no-unlimited-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./.vitepress/components/base/baseHeader.vue')['default']
    Home: typeof import('./.vitepress/components/home.vue')['default']
  }
}
